### ISSUE TITLE
Bug: How do I login into epic acount or minecraft

### ISSUE THREAD

**Issue by exodusScamerr** [Smug246/Luna-Grabber#835]
### What Did You Expect To Happen?

To get a pasword for epic games or to minecraft

### What Happened?

I got some files caled Game User settings, Device profiles or engine 
they are empty 

### Add Screenshots

nah

### Which Options Did You Select?

Games

### How Did You Build The File?

Standard Python

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by exodusScamerr** [comment]
@Smug246

**Comment by NFS11** [comment]
@exodusScamerr the victim problably doesnt have either, or has logged out maybe? either way try again and if it doesnt work then its problably an error
